# Docker Compose Container Infrastructure: Hyperledger Fabric ***CHAINCODE DEV MODE***
# Do *not* run this file directly (using Docker Compose)!
# See the '.env' file for the variables
version: "3.7"

# One network is used to provide inter-org Fabric communication, for accessing the IPFS APIs, and for exposing the Hyperledger Fabric Gateway(s). This network is created by the IPFS compose file.
networks:
  demo:
    external:
      name: ${DEMO_NETWORK_NAME}

services:
  tools.fabric-ccdev.localhost:
    image: "hyperledger/fabric-tools:${FABRIC_VERSION}"
    container_name: tools.fabric-ccdev.localhost
    tty: true
    working_dir: /var/hyperledger/config
    command: /bin/bash
    user: "${FABRIC_TOOLS_UID}:${FABRIC_TOOLS_GID}" # Docker host UID & GID (i.e. your user account; needed for bind mounts)
    volumes:
      - ./fabric-config/:/var/hyperledger/config
    networks:
      - demo

  cc-builder-nodejs-image.fabric-ccdev.localhost:
    build: # Own Node.js image used for building and running the chaincode
      context:  ../fabric/fabric-docker/nodejs-image/
      dockerfile: fabric-nodejs.dockerfile
      args:
        NODE_VERSION: "${CHAINCODE_NODE_VERSION}"
    image: "${COMPOSE_PROJECT_NAME}-nodejs:${CHAINCODE_NODE_VERSION}-alpine"
    container_name: cc-builder-nodejs-image.fabric-ccdev.localhost
    command: /bin/true # Placeholder; we only use this container to enforce the image build
    networks:
      - demo

  orderer0.fabric-ccdev.localhost:
    container_name: orderer0.fabric-ccdev.localhost
    image: hyperledger/fabric-orderer:${FABRIC_VERSION}
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    working_dir: /var/hyperledger/config
    command: orderer
    volumes:
      - ./fabric-config/:/var/hyperledger/config
    networks:
      - demo
  
  peer0.fabric-ccdev.localhost:
    container_name: peer0.fabric-ccdev.localhost
    image: hyperledger/fabric-peer:${FABRIC_VERSION}
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=chaincode=debug
      - CORE_PEER_ID=peer0.fabric-ccdev.localhost
      - CORE_CHAINCODE_LOGLEVEL=debug
      - CORE_CHAINCODE_ID_NAME=ccdevmode:0.1
    working_dir: /var/hyperledger/config
    command: peer node start --peer-chaincodedev=true
    volumes:
      - ./fabric-config/:/var/hyperledger/config
    networks:
      - demo
