# Docker Compose Container Infrastructure: IPFS
# Based, in part, on: https://github.com/ipfs/ipfs-cluster/blob/v0.14.2/docker-compose.yml
# First bootstrap the IPFS nodes!
# See the '.env' file for the variables
version: "3.7"


# A single (layer 3 / IP) network is used to provide the private IPFS network(s) ('pnet0' and 'pnet1'), IPFS cluster traffic, and IPFS' APIs.
# Advanced (production) network topologies are not accounted for in this demo.
networks:
  demo:
    name: ${DEMO_NETWORK_NAME}
    external: True


# IPFS peer service template
x-ipfs-peer: &default-ipfs-peer
  build: # Own IPFS image with private network bootstrap, mDNS toggle, and AutoRelay toggle support
    context: ./peer-image/
    dockerfile: ipfs-peer.dockerfile
    args:
      IPFS_VERSION: "${IPFS_PEER_VERSION}"
  image: "jc_demo_go-ipfs:${IPFS_PEER_VERSION}"
  init: false # Image is already using 'tini' by default
  user: "${IPFS_UID}:${IPFS_GID}" # Docker host UID & GID (i.e. your user account; needed for bind mounts)
  networks:
    - demo
  environment: &env-default-ipfs-peer
    LIBP2P_FORCE_PNET: 1 # Force usage of private IPFS network (daemon fails to start if no config present)
    IPFS_SWARM_KEY: "${IPFS_PNET0_SWARM_KEY}" # Private IPFS network key
    IPFS_PNET_BOOTSTRAP_PEERS: "${IPFS_PNET0_BOOTSTRAP_PEERS}" # Semicolon-separated list of bootstrap nodes for private IPFS networks (peer0 of each pnet)
    IPFS_MDNS: 'false' # Disable multicast DNS peer discovery (we use the Kademlia DHT instead)


# IPFS cluster service template
x-ipfs-cluster: &default-ipfs-cluster
  image: "ipfs/ipfs-cluster:${IPFS_CLUSTER_VERSION}"
  init: false # Image is already using 'tini' by default
  user: "${IPFS_UID}:${IPFS_GID}" # Docker host UID & GID (i.e. your user account; needed for bind mounts)
  networks:
    - demo
  environment: &env-default-ipfs-cluster
    CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in cluster
    CLUSTER_PINSVCAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9097 # Expose Pinning Services API (experimental since v1.0.0)
    CLUSTER_PINSVCAPI_CORSALLOWEDMETHODS: 'GET,POST' # Allow adding of pins
    CLUSTER_PINSVCAPI_SSLCERTFILE: /data/crypto-config/pinsvcapi.crt # TLS certificate
    CLUSTER_PINSVCAPI_SSLKEYFILE: /data/crypto-config/pinsvcapi.key # TLS key
    CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    CLUSTER_METRICS_ENABLESTATS: 'true' # Enable metrics gathering via Prometheus
    CLUSTER_METRICS_PROMETHEUSENDPOINT: '/ip4/0.0.0.0/tcp/8888' # Set Prometheus endpoint to listen on all interfaces


services:
  # Organization A
  # 1 private IPFS network (pnet0) - 1 cluster - 2 peers - 2 cluster sidecars
  peer0.pnet0.orga.ipfs.localhost:
    <<: *default-ipfs-peer
    container_name: peer0.pnet0.orga.ipfs.localhost
    hostname: peer0.pnet0.orga.ipfs.localhost
    volumes:
      - ../ipfs-data/orga/pnet0/peer0:/data/ipfs
    ports:
      - "${IPFS_ORGA_PNET0_PEER0_LIBP2P_SOCKET}:4001" # Allow access from remote JupyterLab (SSH tunnel)
  cluster0.pnet0.orga.ipfs.localhost:
    <<: *default-ipfs-cluster
    container_name: cluster0.pnet0.orga.ipfs.localhost
    hostname: cluster0.pnet0.orga.ipfs.localhost
    depends_on:
      - peer0.pnet0.orga.ipfs.localhost
    environment:
      <<: *env-default-ipfs-cluster
      CLUSTER_PEERNAME: cluster0.pnet0.orga.ipfs.localhost
      CLUSTER_SECRET: ${IPFS_ORGA_PNET0_CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/peer0.pnet0.orga.ipfs.localhost/tcp/5001
      CLUSTER_PINSVCAPI_BASICAUTHCREDENTIALS: ${IPFS_ORGA_PNET0_PINSVCAPI_BASIC_AUTH}
    volumes:
      - ../ipfs-data/orga/pnet0/cluster0:/data/ipfs-cluster
      - ../crypto-config/orga/pnet0/cluster0:/data/crypto-config:ro
  peer1.pnet0.orga.ipfs.localhost:
    <<: *default-ipfs-peer
    container_name: peer1.pnet0.orga.ipfs.localhost
    hostname: peer1.pnet0.orga.ipfs.localhost
    ports:
      - "${IPFS_ORGA_PNET0_PEER1_API_SOCKET}:5001" # Open Peer API RPC port (allows Web UI usage on Docker host)
    volumes:
      - ../ipfs-data/orga/pnet0/peer1:/data/ipfs
  cluster1.pnet0.orga.ipfs.localhost:
    <<: *default-ipfs-cluster
    container_name: cluster1.pnet0.orga.ipfs.localhost
    hostname: cluster1.pnet0.orga.ipfs.localhost
    depends_on:
      - peer1.pnet0.orga.ipfs.localhost
    environment:
      <<: *env-default-ipfs-cluster
      CLUSTER_PEERNAME: cluster1.pnet0.orga.ipfs.localhost
      CLUSTER_SECRET: ${IPFS_ORGA_PNET0_CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/peer1.pnet0.orga.ipfs.localhost/tcp/5001
      CLUSTER_PINSVCAPI_BASICAUTHCREDENTIALS: ${IPFS_ORGA_PNET0_PINSVCAPI_BASIC_AUTH} # Enable HTTP Basic Authentication on the Pinning Services API
    volumes:
      - ../ipfs-data/orga/pnet0/cluster1:/data/ipfs-cluster
      - ../crypto-config/orga/pnet0/cluster1:/data/crypto-config:ro
    networks:
      - demo

  # Organization B
  # 2 private IPFS networks (pnet0 & pnet1) - 2 cluster (1 cluster per private network) - 2 peers per cluster - 2 cluster sidecars per cluster
  # pnet0
  peer0.pnet0.orgb.ipfs.localhost:
    <<: *default-ipfs-peer
    container_name: peer0.pnet0.orgb.ipfs.localhost
    hostname: peer0.pnet0.orgb.ipfs.localhost
    volumes:
      - ../ipfs-data/orgb/pnet0/peer0:/data/ipfs
  cluster0.pnet0.orgb.ipfs.localhost:
    <<: *default-ipfs-cluster
    container_name: cluster0.pnet0.orgb.ipfs.localhost
    hostname: cluster0.pnet0.orgb.ipfs.localhost
    depends_on:
      - peer0.pnet0.orgb.ipfs.localhost
    environment:
      <<: *env-default-ipfs-cluster
      CLUSTER_PEERNAME: cluster0.pnet0.orgb.ipfs.localhost
      CLUSTER_SECRET: ${IPFS_ORGB_PNET0_CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/peer0.pnet0.orgb.ipfs.localhost/tcp/5001
      CLUSTER_PINSVCAPI_BASICAUTHCREDENTIALS: ${IPFS_ORGB_PNET0_PINSVCAPI_BASIC_AUTH}
    volumes:
      - ../ipfs-data/orgb/pnet0/cluster0:/data/ipfs-cluster
      - ../crypto-config/orgb/pnet0/cluster0:/data/crypto-config:ro
  peer1.pnet0.orgb.ipfs.localhost:
    <<: *default-ipfs-peer
    container_name: peer1.pnet0.orgb.ipfs.localhost
    hostname: peer1.pnet0.orgb.ipfs.localhost
    ports:
      - "${IPFS_ORGB_PNET0_PEER1_API_SOCKET}:5001"
    volumes:
      - ../ipfs-data/orgb/pnet0/peer1:/data/ipfs
  cluster1.pnet0.orgb.ipfs.localhost:
    <<: *default-ipfs-cluster
    container_name: cluster1.pnet0.orgb.ipfs.localhost
    hostname: cluster1.pnet0.orgb.ipfs.localhost
    depends_on:
      - peer1.pnet0.orgb.ipfs.localhost
    environment:
      <<: *env-default-ipfs-cluster
      CLUSTER_PEERNAME: cluster1.pnet0.orgb.ipfs.localhost
      CLUSTER_SECRET: ${IPFS_ORGB_PNET0_CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/peer1.pnet0.orgb.ipfs.localhost/tcp/5001
      CLUSTER_PINSVCAPI_BASICAUTHCREDENTIALS: ${IPFS_ORGB_PNET0_PINSVCAPI_BASIC_AUTH}
    volumes:
      - ../ipfs-data/orgb/pnet0/cluster1:/data/ipfs-cluster
      - ../crypto-config/orgb/pnet0/cluster1:/data/crypto-config:ro
  # pnet1
  peer0.pnet1.orgb.ipfs.localhost:
    <<: *default-ipfs-peer
    container_name: peer0.pnet1.orgb.ipfs.localhost
    hostname: peer0.pnet1.orgb.ipfs.localhost
    environment:
      <<: *env-default-ipfs-peer
      IPFS_PNET_BOOTSTRAP_PEERS: ${IPFS_PNET1_BOOTSTRAP_PEERS}
      IPFS_SWARM_KEY: ${IPFS_PNET1_SWARM_KEY}
    volumes:
      - ../ipfs-data/orgb/pnet1/peer0:/data/ipfs
  cluster0.pnet1.orgb.ipfs.localhost:
    <<: *default-ipfs-cluster
    container_name: cluster0.pnet1.orgb.ipfs.localhost
    hostname: cluster0.pnet1.orgb.ipfs.localhost
    depends_on:
      - peer0.pnet1.orgb.ipfs.localhost
    environment:
      <<: *env-default-ipfs-cluster
      CLUSTER_PEERNAME: cluster0.pnet1.orgb.ipfs.localhost
      CLUSTER_SECRET: ${IPFS_ORGB_PNET1_CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/peer0.pnet1.orgb.ipfs.localhost/tcp/5001
      CLUSTER_PINSVCAPI_BASICAUTHCREDENTIALS: ${IPFS_ORGB_PNET1_PINSVCAPI_BASIC_AUTH}
    volumes:
      - ../ipfs-data/orgb/pnet1/cluster0:/data/ipfs-cluster
      - ../crypto-config/orgb/pnet1/cluster0:/data/crypto-config:ro
  peer1.pnet1.orgb.ipfs.localhost:
    <<: *default-ipfs-peer
    container_name: peer1.pnet1.orgb.ipfs.localhost
    hostname: peer1.pnet1.orgb.ipfs.localhost
    environment:
      <<: *env-default-ipfs-peer
      IPFS_PNET_BOOTSTRAP_PEERS: ${IPFS_PNET1_BOOTSTRAP_PEERS}
      IPFS_SWARM_KEY: ${IPFS_PNET1_SWARM_KEY}
    ports:
      - "${IPFS_ORGB_PNET1_PEER1_API_SOCKET}:5001"
    volumes:
      - ../ipfs-data/orgb/pnet1/peer1:/data/ipfs
  cluster1.pnet1.orgb.ipfs.localhost:
    <<: *default-ipfs-cluster
    container_name: cluster1.pnet1.orgb.ipfs.localhost
    hostname: cluster1.pnet1.orgb.ipfs.localhost
    depends_on:
      - peer1.pnet1.orgb.ipfs.localhost
    environment:
      <<: *env-default-ipfs-cluster
      CLUSTER_PEERNAME: cluster1.pnet1.orgb.ipfs.localhost
      CLUSTER_SECRET: ${IPFS_ORGB_PNET1_CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/peer1.pnet1.orgb.ipfs.localhost/tcp/5001
      CLUSTER_PINSVCAPI_BASICAUTHCREDENTIALS: ${IPFS_ORGB_PNET1_PINSVCAPI_BASIC_AUTH}
    volumes:
      - ../ipfs-data/orgb/pnet1/cluster1:/data/ipfs-cluster
      - ../crypto-config/orgb/pnet1/cluster1:/data/crypto-config:ro

  # Organization C
  # 1 private IPFS network (pnet0) - 1 cluster - 2 peers - 2 cluster sidecars
  peer0.pnet0.orgc.ipfs.localhost:
    <<: *default-ipfs-peer
    container_name: peer0.pnet0.orgc.ipfs.localhost
    hostname: peer0.pnet0.orgc.ipfs.localhost
    volumes:
      - ../ipfs-data/orgc/pnet0/peer0:/data/ipfs
  cluster0.pnet0.orgc.ipfs.localhost:
    <<: *default-ipfs-cluster
    container_name: cluster0.pnet0.orgc.ipfs.localhost
    hostname: cluster0.pnet0.orgc.ipfs.localhost
    depends_on:
      - peer0.pnet0.orgc.ipfs.localhost
    environment:
      <<: *env-default-ipfs-cluster
      CLUSTER_PEERNAME: cluster0.pnet0.orgc.ipfs.localhost
      CLUSTER_SECRET: ${IPFS_ORGC_PNET0_CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/peer0.pnet0.orgc.ipfs.localhost/tcp/5001
      CLUSTER_PINSVCAPI_BASICAUTHCREDENTIALS: ${IPFS_ORGC_PNET0_PINSVCAPI_BASIC_AUTH}
    volumes:
      - ../ipfs-data/orgc/pnet0/cluster0:/data/ipfs-cluster
      - ../crypto-config/orgc/pnet0/cluster0:/data/crypto-config:ro
  peer1.pnet0.orgc.ipfs.localhost:      
    <<: *default-ipfs-peer
    container_name: peer1.pnet0.orgc.ipfs.localhost
    hostname: peer1.pnet0.orgc.ipfs.localhost
    ports:
      - "${IPFS_ORGC_PNET0_PEER1_API_SOCKET}:5001"
    volumes:
      - ../ipfs-data/orgc/pnet0/peer1:/data/ipfs
  cluster1.pnet0.orgc.ipfs.localhost:
    <<: *default-ipfs-cluster
    container_name: cluster1.pnet0.orgc.ipfs.localhost
    hostname: cluster1.pnet0.orgc.ipfs.localhost
    depends_on:
      - peer1.pnet0.orgc.ipfs.localhost
    environment:
      <<: *env-default-ipfs-cluster
      CLUSTER_PEERNAME: cluster1.pnet0.orgc.ipfs.localhost
      CLUSTER_SECRET: ${IPFS_ORGC_PNET0_CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/peer1.pnet0.orgc.ipfs.localhost/tcp/5001
      CLUSTER_PINSVCAPI_BASICAUTHCREDENTIALS: ${IPFS_ORGC_PNET0_PINSVCAPI_BASIC_AUTH}
    volumes:
      - ../ipfs-data/orgc/pnet0/cluster1:/data/ipfs-cluster
      - ../crypto-config/orgc/pnet0/cluster1:/data/crypto-config:ro
